name = "streamhuddle"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-25"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_CONVEX_URL = "https://sincere-clownfish-686.convex.cloud"
VITE_CONVEX_SITE_URL = "https://sincere-clownfish-686.convex.site"
SITE_URL = "https://streamhuddle.pages.dev"
VITE_SITE_URL = "https://streamhuddle.pages.dev"
