/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StreamerUsernameRouteImport } from './routes/streamer.$username'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as ApiTwitchConnectRouteImport } from './routes/api/twitch/connect'
import { Route as ApiTwitchCallbackRouteImport } from './routes/api/twitch/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamerUsernameRoute = StreamerUsernameRouteImport.update({
  id: '/streamer/$username',
  path: '/streamer/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTwitchConnectRoute = ApiTwitchConnectRouteImport.update({
  id: '/api/twitch/connect',
  path: '/api/twitch/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwitchCallbackRoute = ApiTwitchCallbackRouteImport.update({
  id: '/api/twitch/callback',
  path: '/api/twitch/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/roster': typeof RosterRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/university': typeof UniversityRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/streamer/$username': typeof StreamerUsernameRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/twitch/callback': typeof ApiTwitchCallbackRoute
  '/api/twitch/connect': typeof ApiTwitchConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/roster': typeof RosterRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/university': typeof UniversityRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/streamer/$username': typeof StreamerUsernameRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/twitch/callback': typeof ApiTwitchCallbackRoute
  '/api/twitch/connect': typeof ApiTwitchConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/roster': typeof RosterRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/university': typeof UniversityRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/streamer/$username': typeof StreamerUsernameRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/twitch/callback': typeof ApiTwitchCallbackRoute
  '/api/twitch/connect': typeof ApiTwitchConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/pricing'
    | '/roster'
    | '/sign-in'
    | '/sign-up'
    | '/university'
    | '/admin'
    | '/profile'
    | '/blog/$slug'
    | '/category/$categoryId'
    | '/streamer/$username'
    | '/blog/'
    | '/api/auth/$'
    | '/api/twitch/callback'
    | '/api/twitch/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/pricing'
    | '/roster'
    | '/sign-in'
    | '/sign-up'
    | '/university'
    | '/admin'
    | '/profile'
    | '/blog/$slug'
    | '/category/$categoryId'
    | '/streamer/$username'
    | '/blog'
    | '/api/auth/$'
    | '/api/twitch/callback'
    | '/api/twitch/connect'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/discover'
    | '/pricing'
    | '/roster'
    | '/sign-in'
    | '/sign-up'
    | '/university'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/blog/$slug'
    | '/category/$categoryId'
    | '/streamer/$username'
    | '/blog/'
    | '/api/auth/$'
    | '/api/twitch/callback'
    | '/api/twitch/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  PricingRoute: typeof PricingRoute
  RosterRoute: typeof RosterRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UniversityRoute: typeof UniversityRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  StreamerUsernameRoute: typeof StreamerUsernameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTwitchCallbackRoute: typeof ApiTwitchCallbackRoute
  ApiTwitchConnectRoute: typeof ApiTwitchConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamer/$username': {
      id: '/streamer/$username'
      path: '/streamer/$username'
      fullPath: '/streamer/$username'
      preLoaderRoute: typeof StreamerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/twitch/connect': {
      id: '/api/twitch/connect'
      path: '/api/twitch/connect'
      fullPath: '/api/twitch/connect'
      preLoaderRoute: typeof ApiTwitchConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twitch/callback': {
      id: '/api/twitch/callback'
      path: '/api/twitch/callback'
      fullPath: '/api/twitch/callback'
      preLoaderRoute: typeof ApiTwitchCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedProfileRoute: AuthedProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  PricingRoute: PricingRoute,
  RosterRoute: RosterRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UniversityRoute: UniversityRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  StreamerUsernameRoute: StreamerUsernameRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTwitchCallbackRoute: ApiTwitchCallbackRoute,
  ApiTwitchConnectRoute: ApiTwitchConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
